TARGET=OSFA-Benchmarks

# Bins
MAKE=make
CPP=g++
CFLAGS=-g
LFLAGS=-lpthread

# Support files
SUPPORT_PATH=testcasesupport/
INCLUDES=$(SUPPORT_PATH)
SUPPORT_SRCS=$(addprefix $(SUPPORT_PATH),main_linux.cpp io.c std_thread.c)
SUPPORT_OBJS=$(addsuffix .o,$(SUPPORT_SRCS))

# Partial files
MAKE_FILES=$(wildcard testcases/*/s*/Makefile) $(wildcard testcases/*/Makefile)
PARTIALS=$(patsubst %Makefile,%partial,$(MAKE_FILES))
INDIVIDUALS=$(patsubst %Makefile,%individuals,$(MAKE_FILES))

$(TARGET): $(PARTIALS) $(SUPPORT_OBJS)
	$(CPP) $(CFLAGS) -I $(INCLUDES) -o $@ $(addsuffix .o,$(PARTIALS)) $(SUPPORT_OBJS) $(LFLAGS)

$(PARTIALS): 
	$(MAKE) -C $(dir $@) $(notdir $@).o

individuals: $(INDIVIDUALS)

$(INDIVIDUALS):
	$(MAKE) -C $(dir $@) $(notdir $@)
# clang -O1 -fsanitize=address -fno-omit-frame-pointer -C $(dir $@) $(notdir $@)

$(SUPPORT_OBJS): $(SUPPORT_SRCS)
	$(CPP) $(CFLAGS) -c -I $(INCLUDES) -o $@ $(@:.o=) $(LFLAGS)
clean:
	rm -rf *.out $(TARGET) testcases/CWE121_Stack_Based_Buffer_Overflow/s01/*.o testcases/CWE121_Stack_Based_Buffer_Overflow/s01/*.out testcases/CWE121_Stack_Based_Buffer_Overflow/s01/*.txt testcases/CWE122_Heap_Based_Buffer_Overflow/s01/*.o testcases/CWE122_Heap_Based_Buffer_Overflow/s01/*.out testcases/CWE122_Heap_Based_Buffer_Overflow/s01/*.txt testcases/CWE124_Buffer_Underwrite/s01/*.o testcases/CWE124_Buffer_Underwrite/s01/*.out testcases/CWE124_Buffer_Underwrite/s01/*.txt testcases/CWE126_Buffer_Overread/s01/*.o testcases/CWE126_Buffer_Overread/s01/*.out testcases/CWE126_Buffer_Overread/s01/*.txt testcases/CWE127_Buffer_Underread/s01/*.o testcases/CWE127_Buffer_Underread/s01/*.out testcases/CWE127_Buffer_Underread/s01/*.txt testcases/CWE190_Integer_Overflow/s01/*.o testcases/CWE190_Integer_Overflow/s01/*.out testcases/CWE190_Integer_Overflow/s01/*.txt testcases/CWE191_Integer_Underflow/s01/*.o testcases/CWE191_Integer_Underflow/s01/*.out testcases/CWE191_Integer_Underflow/s01/*.txt
