/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__char_type_overrun_memcpy_01_good();");
	CWE122_Heap_Based_Buffer_Overflow__char_type_overrun_memcpy_01_good();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__char_type_overrun_memcpy_02_good();");
	CWE122_Heap_Based_Buffer_Overflow__char_type_overrun_memcpy_02_good();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__char_type_overrun_memmove_02_good();");
	CWE122_Heap_Based_Buffer_Overflow__char_type_overrun_memmove_02_good();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__char_type_overrun_memmove_01_good();");
	CWE122_Heap_Based_Buffer_Overflow__char_type_overrun_memmove_01_good();

	/* END-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */





#ifdef __cplusplus
	/* Calling C++ good functions */
	/* BEGIN-AUTOGENERATED-CPP-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_fscanf_01::good();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_fscanf_01::good();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_listen_socket_01::good();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_listen_socket_01::good();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_fgets_01::good();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_fgets_01::good();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_connect_socket_02::good();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_connect_socket_02::good();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_large_01::good();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_large_01::good();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_ncpy_01::good();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_ncpy_01::good();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_loop_02::good();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_loop_02::good();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_cpy_01::good();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_cpy_01::good();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_cpy_02::good();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_cpy_02::good();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_ncpy_02::good();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_ncpy_02::good();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_fscanf_02::good();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_fscanf_02::good();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_listen_socket_02::good();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_listen_socket_02::good();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_memcpy_02::good();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_memcpy_02::good();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_memmove_01::good();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_memmove_01::good();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_large_02::good();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_large_02::good();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_memcpy_01::good();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_memcpy_01::good();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_memmove_02::good();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_memmove_02::good();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_rand_01::good();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_rand_01::good();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_fgets_02::good();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_fgets_02::good();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_loop_01::good();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_loop_01::good();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_connect_socket_01::good();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_connect_socket_01::good();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_rand_02::good();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_rand_02::good();

	/* END-AUTOGENERATED-CPP-GOOD-FUNCTION-CALLS */

#endif /* __cplusplus */

#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__char_type_overrun_memcpy_01_bad();");
	CWE122_Heap_Based_Buffer_Overflow__char_type_overrun_memcpy_01_bad();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__char_type_overrun_memcpy_02_bad();");
	CWE122_Heap_Based_Buffer_Overflow__char_type_overrun_memcpy_02_bad();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__char_type_overrun_memmove_02_bad();");
	CWE122_Heap_Based_Buffer_Overflow__char_type_overrun_memmove_02_bad();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__char_type_overrun_memmove_01_bad();");
	CWE122_Heap_Based_Buffer_Overflow__char_type_overrun_memmove_01_bad();

	/* END-AUTOGENERATED-C-BAD-FUNCTION-CALLS */




	
#ifdef __cplusplus
	/* Calling C++ bad functions */
	/* BEGIN-AUTOGENERATED-CPP-BAD-FUNCTION-CALLS */
	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_fscanf_01::bad();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_fscanf_01::bad();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_listen_socket_01::bad();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_listen_socket_01::bad();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_fgets_01::bad();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_fgets_01::bad();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_connect_socket_02::bad();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_connect_socket_02::bad();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_large_01::bad();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_large_01::bad();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_ncpy_01::bad();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_ncpy_01::bad();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_loop_02::bad();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_loop_02::bad();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_cpy_01::bad();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_cpy_01::bad();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_cpy_02::bad();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_cpy_02::bad();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_ncpy_02::bad();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_ncpy_02::bad();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_fscanf_02::bad();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_fscanf_02::bad();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_listen_socket_02::bad();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_listen_socket_02::bad();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_memcpy_02::bad();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_memcpy_02::bad();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_memmove_01::bad();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_memmove_01::bad();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_large_02::bad();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_large_02::bad();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_memcpy_01::bad();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_memcpy_01::bad();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_memmove_02::bad();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_memmove_02::bad();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_rand_01::bad();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_rand_01::bad();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_fgets_02::bad();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_fgets_02::bad();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_loop_01::bad();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE193_char_loop_01::bad();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_connect_socket_01::bad();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_connect_socket_01::bad();

	printLine("Calling CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_rand_02::bad();");
	CWE122_Heap_Based_Buffer_Overflow__cpp_CWE129_rand_02::bad();

	/* END-AUTOGENERATED-CPP-BAD-FUNCTION-CALLS */
	
#endif /* __cplusplus */

#endif /* OMITBAD */

	return 0;

} 
