// NOTE - eventually this file will be automatically updated using a Perl script that understand
// the naming of test case files, functions, and namespaces.

#ifndef _TESTCASES_H
#define _TESTCASES_H

#ifdef __cplusplus
extern "C" {
#endif

// declare C good and bad functions
#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */
	void CWE127_Buffer_Underread__CWE839_connect_socket_01_good();

	void CWE127_Buffer_Underread__char_declare_memcpy_02_good();

	void CWE127_Buffer_Underread__CWE839_listen_socket_02_good();

	void CWE127_Buffer_Underread__char_declare_loop_01_good();

	void CWE127_Buffer_Underread__char_declare_memmove_01_good();

	void CWE127_Buffer_Underread__char_alloca_memmove_02_good();

	void CWE127_Buffer_Underread__CWE839_fgets_02_good();

	void CWE127_Buffer_Underread__char_alloca_cpy_01_good();

	void CWE127_Buffer_Underread__CWE839_listen_socket_01_good();

	void CWE127_Buffer_Underread__char_alloca_loop_01_good();

	void CWE127_Buffer_Underread__char_alloca_ncpy_02_good();

	void CWE127_Buffer_Underread__char_declare_loop_02_good();

	void CWE127_Buffer_Underread__char_declare_ncpy_01_good();

	void CWE127_Buffer_Underread__CWE839_fscanf_02_good();

	void CWE127_Buffer_Underread__char_declare_cpy_01_good();

	void CWE127_Buffer_Underread__char_declare_ncpy_02_good();

	void CWE127_Buffer_Underread__CWE839_fgets_01_good();

	void CWE127_Buffer_Underread__char_declare_memcpy_01_good();

	void CWE127_Buffer_Underread__char_alloca_ncpy_01_good();

	void CWE127_Buffer_Underread__char_declare_memmove_02_good();

	void CWE127_Buffer_Underread__char_declare_cpy_02_good();

	void CWE127_Buffer_Underread__CWE839_fscanf_01_good();

	void CWE127_Buffer_Underread__char_alloca_loop_02_good();

	void CWE127_Buffer_Underread__char_alloca_memcpy_01_good();

	void CWE127_Buffer_Underread__char_alloca_cpy_02_good();

	void CWE127_Buffer_Underread__char_alloca_memmove_01_good();

	void CWE127_Buffer_Underread__CWE839_connect_socket_02_good();

	void CWE127_Buffer_Underread__char_alloca_memcpy_02_good();

	/* END-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
	void CWE127_Buffer_Underread__CWE839_connect_socket_01_bad();

	void CWE127_Buffer_Underread__char_declare_memcpy_02_bad();

	void CWE127_Buffer_Underread__CWE839_listen_socket_02_bad();

	void CWE127_Buffer_Underread__char_declare_loop_01_bad();

	void CWE127_Buffer_Underread__char_declare_memmove_01_bad();

	void CWE127_Buffer_Underread__char_alloca_memmove_02_bad();

	void CWE127_Buffer_Underread__CWE839_fgets_02_bad();

	void CWE127_Buffer_Underread__char_alloca_cpy_01_bad();

	void CWE127_Buffer_Underread__CWE839_listen_socket_01_bad();

	void CWE127_Buffer_Underread__char_alloca_loop_01_bad();

	void CWE127_Buffer_Underread__char_alloca_ncpy_02_bad();

	void CWE127_Buffer_Underread__char_declare_loop_02_bad();

	void CWE127_Buffer_Underread__char_declare_ncpy_01_bad();

	void CWE127_Buffer_Underread__CWE839_fscanf_02_bad();

	void CWE127_Buffer_Underread__char_declare_cpy_01_bad();

	void CWE127_Buffer_Underread__char_declare_ncpy_02_bad();

	void CWE127_Buffer_Underread__CWE839_fgets_01_bad();

	void CWE127_Buffer_Underread__char_declare_memcpy_01_bad();

	void CWE127_Buffer_Underread__char_alloca_ncpy_01_bad();

	void CWE127_Buffer_Underread__char_declare_memmove_02_bad();

	void CWE127_Buffer_Underread__char_declare_cpy_02_bad();

	void CWE127_Buffer_Underread__CWE839_fscanf_01_bad();

	void CWE127_Buffer_Underread__char_alloca_loop_02_bad();

	void CWE127_Buffer_Underread__char_alloca_memcpy_01_bad();

	void CWE127_Buffer_Underread__char_alloca_cpy_02_bad();

	void CWE127_Buffer_Underread__char_alloca_memmove_01_bad();

	void CWE127_Buffer_Underread__CWE839_connect_socket_02_bad();

	void CWE127_Buffer_Underread__char_alloca_memcpy_02_bad();

	/* END-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD

#ifdef __cplusplus
} // end extern "C"
#endif

#ifdef __cplusplus
// declare C++ namespaces and good and bad functions

#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */

	/* END-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */

	/* END-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD


#endif // __cplusplus


#endif //  _TESTCASES_H
