// NOTE - eventually this file will be automatically updated using a Perl script that understand
// the naming of test case files, functions, and namespaces.

#ifndef _TESTCASES_H
#define _TESTCASES_H

#ifdef __cplusplus
extern "C" {
#endif

// declare C good and bad functions
#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */
	void CWE190_Integer_Overflow__char_rand_multiply_01_good();

	void CWE190_Integer_Overflow__char_max_square_01_good();

	void CWE190_Integer_Overflow__char_rand_square_01_good();

	void CWE190_Integer_Overflow__int64_t_fscanf_multiply_02_good();

	void CWE190_Integer_Overflow__char_fscanf_add_02_good();

	void CWE190_Integer_Overflow__int64_t_fscanf_add_02_good();

	void CWE190_Integer_Overflow__char_rand_multiply_02_good();

	void CWE190_Integer_Overflow__char_fscanf_multiply_01_good();

	void CWE190_Integer_Overflow__char_fscanf_multiply_02_good();

	void CWE190_Integer_Overflow__char_max_multiply_01_good();

	void CWE190_Integer_Overflow__char_rand_add_01_good();

	void CWE190_Integer_Overflow__char_max_add_02_good();

	void CWE190_Integer_Overflow__char_fscanf_add_01_good();

	void CWE190_Integer_Overflow__char_fscanf_square_01_good();

	void CWE190_Integer_Overflow__char_rand_add_02_good();

	void CWE190_Integer_Overflow__char_max_multiply_02_good();

	void CWE190_Integer_Overflow__char_max_square_02_good();

	void CWE190_Integer_Overflow__char_max_add_01_good();

	void CWE190_Integer_Overflow__int64_t_fscanf_add_01_good();

	void CWE190_Integer_Overflow__int64_t_fscanf_multiply_01_good();

	void CWE190_Integer_Overflow__char_rand_square_02_good();

	void CWE190_Integer_Overflow__char_fscanf_square_02_good();

	/* END-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
	void CWE190_Integer_Overflow__char_rand_multiply_01_bad();

	void CWE190_Integer_Overflow__char_max_square_01_bad();

	void CWE190_Integer_Overflow__char_rand_square_01_bad();

	void CWE190_Integer_Overflow__int64_t_fscanf_multiply_02_bad();

	void CWE190_Integer_Overflow__char_fscanf_add_02_bad();

	void CWE190_Integer_Overflow__int64_t_fscanf_add_02_bad();

	void CWE190_Integer_Overflow__char_rand_multiply_02_bad();

	void CWE190_Integer_Overflow__char_fscanf_multiply_01_bad();

	void CWE190_Integer_Overflow__char_fscanf_multiply_02_bad();

	void CWE190_Integer_Overflow__char_max_multiply_01_bad();

	void CWE190_Integer_Overflow__char_rand_add_01_bad();

	void CWE190_Integer_Overflow__char_max_add_02_bad();

	void CWE190_Integer_Overflow__char_fscanf_add_01_bad();

	void CWE190_Integer_Overflow__char_fscanf_square_01_bad();

	void CWE190_Integer_Overflow__char_rand_add_02_bad();

	void CWE190_Integer_Overflow__char_max_multiply_02_bad();

	void CWE190_Integer_Overflow__char_max_square_02_bad();

	void CWE190_Integer_Overflow__char_max_add_01_bad();

	void CWE190_Integer_Overflow__int64_t_fscanf_add_01_bad();

	void CWE190_Integer_Overflow__int64_t_fscanf_multiply_01_bad();

	void CWE190_Integer_Overflow__char_rand_square_02_bad();

	void CWE190_Integer_Overflow__char_fscanf_square_02_bad();

	/* END-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD

#ifdef __cplusplus
} // end extern "C"
#endif

#ifdef __cplusplus
// declare C++ namespaces and good and bad functions

#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */

	/* END-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */

	/* END-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD


#endif // __cplusplus


#endif //  _TESTCASES_H
