// NOTE - eventually this file will be automatically updated using a Perl script that understand
// the naming of test case files, functions, and namespaces.

#ifndef _TESTCASES_H
#define _TESTCASES_H

#ifdef __cplusplus
extern "C" {
#endif

// declare C good and bad functions
#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */
	void CWE121_Stack_Based_Buffer_Overflow__CWE129_fgets_01_good();

	void CWE121_Stack_Based_Buffer_Overflow__CWE129_fscanf_02_good();

	void CWE121_Stack_Based_Buffer_Overflow__CWE129_rand_01_good();

	void CWE121_Stack_Based_Buffer_Overflow__CWE131_memcpy_02_good();

	void CWE121_Stack_Based_Buffer_Overflow__char_type_overrun_memcpy_02_good();

	void CWE121_Stack_Based_Buffer_Overflow__CWE135_01_good();

	void CWE121_Stack_Based_Buffer_Overflow__CWE131_loop_01_good();

	void CWE121_Stack_Based_Buffer_Overflow__CWE131_loop_02_good();

	void CWE121_Stack_Based_Buffer_Overflow__CWE129_rand_02_good();

	void CWE121_Stack_Based_Buffer_Overflow__CWE131_memmove_02_good();

	void CWE121_Stack_Based_Buffer_Overflow__CWE135_02_good();

	void CWE121_Stack_Based_Buffer_Overflow__CWE129_fgets_02_good();

	void CWE121_Stack_Based_Buffer_Overflow__CWE131_memmove_01_good();

	void CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_cpy_01_good();

	void CWE121_Stack_Based_Buffer_Overflow__CWE129_fscanf_01_good();

	void CWE121_Stack_Based_Buffer_Overflow__CWE129_listen_socket_02_good();

	void CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_cpy_02_good();

	void CWE121_Stack_Based_Buffer_Overflow__CWE129_connect_socket_01_good();

	void CWE121_Stack_Based_Buffer_Overflow__CWE129_large_01_good();

	void CWE121_Stack_Based_Buffer_Overflow__CWE131_memcpy_01_good();

	void CWE121_Stack_Based_Buffer_Overflow__CWE129_connect_socket_02_good();

	void CWE121_Stack_Based_Buffer_Overflow__char_type_overrun_memcpy_01_good();

	void CWE121_Stack_Based_Buffer_Overflow__char_type_overrun_memmove_02_good();

	void CWE121_Stack_Based_Buffer_Overflow__CWE129_large_02_good();

	void CWE121_Stack_Based_Buffer_Overflow__char_type_overrun_memmove_01_good();

	void CWE121_Stack_Based_Buffer_Overflow__CWE129_listen_socket_01_good();

	/* END-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
	void CWE121_Stack_Based_Buffer_Overflow__CWE129_fgets_01_bad();

	void CWE121_Stack_Based_Buffer_Overflow__CWE129_fscanf_02_bad();

	void CWE121_Stack_Based_Buffer_Overflow__CWE129_rand_01_bad();

	void CWE121_Stack_Based_Buffer_Overflow__CWE131_memcpy_02_bad();

	void CWE121_Stack_Based_Buffer_Overflow__char_type_overrun_memcpy_02_bad();

	void CWE121_Stack_Based_Buffer_Overflow__CWE135_01_bad();

	void CWE121_Stack_Based_Buffer_Overflow__CWE131_loop_01_bad();

	void CWE121_Stack_Based_Buffer_Overflow__CWE131_loop_02_bad();

	void CWE121_Stack_Based_Buffer_Overflow__CWE129_rand_02_bad();

	void CWE121_Stack_Based_Buffer_Overflow__CWE131_memmove_02_bad();

	void CWE121_Stack_Based_Buffer_Overflow__CWE135_02_bad();

	void CWE121_Stack_Based_Buffer_Overflow__CWE129_fgets_02_bad();

	void CWE121_Stack_Based_Buffer_Overflow__CWE131_memmove_01_bad();

	void CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_cpy_01_bad();

	void CWE121_Stack_Based_Buffer_Overflow__CWE129_fscanf_01_bad();

	void CWE121_Stack_Based_Buffer_Overflow__CWE129_listen_socket_02_bad();

	void CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_cpy_02_bad();

	void CWE121_Stack_Based_Buffer_Overflow__CWE129_connect_socket_01_bad();

	void CWE121_Stack_Based_Buffer_Overflow__CWE129_large_01_bad();

	void CWE121_Stack_Based_Buffer_Overflow__CWE131_memcpy_01_bad();

	void CWE121_Stack_Based_Buffer_Overflow__CWE129_connect_socket_02_bad();

	void CWE121_Stack_Based_Buffer_Overflow__char_type_overrun_memcpy_01_bad();

	void CWE121_Stack_Based_Buffer_Overflow__char_type_overrun_memmove_02_bad();

	void CWE121_Stack_Based_Buffer_Overflow__CWE129_large_02_bad();

	void CWE121_Stack_Based_Buffer_Overflow__char_type_overrun_memmove_01_bad();

	void CWE121_Stack_Based_Buffer_Overflow__CWE129_listen_socket_01_bad();

	/* END-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD

#ifdef __cplusplus
} // end extern "C"
#endif

#ifdef __cplusplus
// declare C++ namespaces and good and bad functions

#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */

	/* END-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */

	/* END-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD


#endif // __cplusplus


#endif //  _TESTCASES_H
